//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseTec.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD1Entities1 : DbContext
    {
        public BD1Entities1()
            : base("name=BD1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiario> Beneficiario { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Estado_Cuenta> Estado_Cuenta { get; set; }
        public virtual DbSet<Parentezco> Parentezco { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Tipo_Cuenta_Ahorros> Tipo_Cuenta_Ahorros { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Tipo_Moneda> Tipo_Moneda { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Visualizacion> Usuario_Visualizacion { get; set; }
        public virtual DbSet<Bitacora_Accion> Bitacora_Accion { get; set; }
        public virtual DbSet<Tipo_Accion> Tipo_Accion { get; set; }
    
        public virtual int Actualizar_Beneficiario_Porcentaje(string inNombre_Persona, string inNum_Cuenta, string inParentezco, Nullable<float> inPorcentaje)
        {
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inParentezcoParameter = inParentezco != null ?
                new ObjectParameter("inParentezco", inParentezco) :
                new ObjectParameter("inParentezco", typeof(string));
    
            var inPorcentajeParameter = inPorcentaje.HasValue ?
                new ObjectParameter("inPorcentaje", inPorcentaje) :
                new ObjectParameter("inPorcentaje", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Beneficiario_Porcentaje", inNombre_PersonaParameter, inNum_CuentaParameter, inParentezcoParameter, inPorcentajeParameter);
        }
    
        public virtual int Cargar_Beneficiario(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Beneficiario", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Cuentas(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Cuentas", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Estado_Cuenta(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Estado_Cuenta", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Parentezco(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Parentezco", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Personas(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Personas", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Cuenta_Ahorros(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Cuenta_Ahorros", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Doc(string tipo_Documento, Nullable<int> doc)
        {
            var tipo_DocumentoParameter = tipo_Documento != null ?
                new ObjectParameter("tipo_Documento", tipo_Documento) :
                new ObjectParameter("tipo_Documento", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Doc", tipo_DocumentoParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Moneda(string tipo_Documento, Nullable<int> doc)
        {
            var tipo_DocumentoParameter = tipo_Documento != null ?
                new ObjectParameter("tipo_Documento", tipo_Documento) :
                new ObjectParameter("tipo_Documento", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Moneda", tipo_DocumentoParameter, docParameter);
        }
    
        public virtual int Cargar_Usuarios(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Usuarios", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Usuarios_Visualizacion(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Usuarios_Visualizacion", datosParameter, docParameter);
        }
    
        public virtual int Crear_Beneficiario(string inNombre_Persona, string inNum_Cuenta, string inParentezco, Nullable<float> inPorcentaje)
        {
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inParentezcoParameter = inParentezco != null ?
                new ObjectParameter("inParentezco", inParentezco) :
                new ObjectParameter("inParentezco", typeof(string));
    
            var inPorcentajeParameter = inPorcentaje.HasValue ?
                new ObjectParameter("inPorcentaje", inPorcentaje) :
                new ObjectParameter("inPorcentaje", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Beneficiario", inNombre_PersonaParameter, inNum_CuentaParameter, inParentezcoParameter, inPorcentajeParameter);
        }
    
        public virtual int Eliminar_Beneficiario(Nullable<int> inId)
        {
            var inIdParameter = inId.HasValue ?
                new ObjectParameter("inId", inId) :
                new ObjectParameter("inId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Beneficiario", inIdParameter);
        }
    
        public virtual ObjectResult<Leer_Beneficiario_Cuenta_Result> Leer_Beneficiario_Cuenta(string inNum_Cuenta)
        {
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Leer_Beneficiario_Cuenta_Result>("Leer_Beneficiario_Cuenta", inNum_CuentaParameter);
        }
    
        public virtual ObjectResult<Leer_Todos_Beneficiario_Result> Leer_Todos_Beneficiario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Leer_Todos_Beneficiario_Result>("Leer_Todos_Beneficiario");
        }
    
        public virtual int Actualizar_Beneficiario(Nullable<int> inId_Beneficiario, string inNombre_Persona, string inNum_Cuenta, Nullable<int> inNombre_Parentezco, Nullable<float> inPorcentaje, string inUsuarioACargo, string inIPusuario)
        {
            var inId_BeneficiarioParameter = inId_Beneficiario.HasValue ?
                new ObjectParameter("inId_Beneficiario", inId_Beneficiario) :
                new ObjectParameter("inId_Beneficiario", typeof(int));
    
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inNombre_ParentezcoParameter = inNombre_Parentezco.HasValue ?
                new ObjectParameter("inNombre_Parentezco", inNombre_Parentezco) :
                new ObjectParameter("inNombre_Parentezco", typeof(int));
    
            var inPorcentajeParameter = inPorcentaje.HasValue ?
                new ObjectParameter("inPorcentaje", inPorcentaje) :
                new ObjectParameter("inPorcentaje", typeof(float));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Beneficiario", inId_BeneficiarioParameter, inNombre_PersonaParameter, inNum_CuentaParameter, inNombre_ParentezcoParameter, inPorcentajeParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Cuenta(Nullable<int> inId_Cuenta, string inNombre_Persona, string inNombre_Tipo_Cuenta_Ahorros, string inNum_Cuenta, Nullable<System.DateTime> inFecha_Creacion, Nullable<decimal> inSaldo, string inUsuarioACargo, string inIPusuario)
        {
            var inId_CuentaParameter = inId_Cuenta.HasValue ?
                new ObjectParameter("inId_Cuenta", inId_Cuenta) :
                new ObjectParameter("inId_Cuenta", typeof(int));
    
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNombre_Tipo_Cuenta_AhorrosParameter = inNombre_Tipo_Cuenta_Ahorros != null ?
                new ObjectParameter("inNombre_Tipo_Cuenta_Ahorros", inNombre_Tipo_Cuenta_Ahorros) :
                new ObjectParameter("inNombre_Tipo_Cuenta_Ahorros", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inFecha_CreacionParameter = inFecha_Creacion.HasValue ?
                new ObjectParameter("inFecha_Creacion", inFecha_Creacion) :
                new ObjectParameter("inFecha_Creacion", typeof(System.DateTime));
    
            var inSaldoParameter = inSaldo.HasValue ?
                new ObjectParameter("inSaldo", inSaldo) :
                new ObjectParameter("inSaldo", typeof(decimal));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Cuenta", inId_CuentaParameter, inNombre_PersonaParameter, inNombre_Tipo_Cuenta_AhorrosParameter, inNum_CuentaParameter, inFecha_CreacionParameter, inSaldoParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Estado_Cuenta(Nullable<int> inId_Estado_Cuenta, string inNum_Cuenta, Nullable<System.DateTime> inFecha_Inicio, Nullable<System.DateTime> inFecha_Fin, Nullable<decimal> inSaldo_Inicial, Nullable<decimal> inSaldo_Final, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Estado_CuentaParameter = inId_Estado_Cuenta.HasValue ?
                new ObjectParameter("inId_Estado_Cuenta", inId_Estado_Cuenta) :
                new ObjectParameter("inId_Estado_Cuenta", typeof(int));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inFecha_InicioParameter = inFecha_Inicio.HasValue ?
                new ObjectParameter("inFecha_Inicio", inFecha_Inicio) :
                new ObjectParameter("inFecha_Inicio", typeof(System.DateTime));
    
            var inFecha_FinParameter = inFecha_Fin.HasValue ?
                new ObjectParameter("inFecha_Fin", inFecha_Fin) :
                new ObjectParameter("inFecha_Fin", typeof(System.DateTime));
    
            var inSaldo_InicialParameter = inSaldo_Inicial.HasValue ?
                new ObjectParameter("inSaldo_Inicial", inSaldo_Inicial) :
                new ObjectParameter("inSaldo_Inicial", typeof(decimal));
    
            var inSaldo_FinalParameter = inSaldo_Final.HasValue ?
                new ObjectParameter("inSaldo_Final", inSaldo_Final) :
                new ObjectParameter("inSaldo_Final", typeof(decimal));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Estado_Cuenta", inId_Estado_CuentaParameter, inNum_CuentaParameter, inFecha_InicioParameter, inFecha_FinParameter, inSaldo_InicialParameter, inSaldo_FinalParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Parentezco(Nullable<int> inId_Parentezco, string inNombre, string inUsuarioACargo, string inIPusuario)
        {
            var inId_ParentezcoParameter = inId_Parentezco.HasValue ?
                new ObjectParameter("inId_Parentezco", inId_Parentezco) :
                new ObjectParameter("inId_Parentezco", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Parentezco", inId_ParentezcoParameter, inNombreParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Persona(Nullable<int> inId_Persona, string inNombre, string inTipoDocumento, string inDocumento_Identidad, Nullable<System.DateTime> inFecha_Nacimiento, string inEmail, string inTelefono1, string inTelefono2, string inUsuarioACargo, string inIPusuario)
        {
            var inId_PersonaParameter = inId_Persona.HasValue ?
                new ObjectParameter("inId_Persona", inId_Persona) :
                new ObjectParameter("inId_Persona", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inTipoDocumentoParameter = inTipoDocumento != null ?
                new ObjectParameter("inTipoDocumento", inTipoDocumento) :
                new ObjectParameter("inTipoDocumento", typeof(string));
    
            var inDocumento_IdentidadParameter = inDocumento_Identidad != null ?
                new ObjectParameter("inDocumento_Identidad", inDocumento_Identidad) :
                new ObjectParameter("inDocumento_Identidad", typeof(string));
    
            var inFecha_NacimientoParameter = inFecha_Nacimiento.HasValue ?
                new ObjectParameter("inFecha_Nacimiento", inFecha_Nacimiento) :
                new ObjectParameter("inFecha_Nacimiento", typeof(System.DateTime));
    
            var inEmailParameter = inEmail != null ?
                new ObjectParameter("inEmail", inEmail) :
                new ObjectParameter("inEmail", typeof(string));
    
            var inTelefono1Parameter = inTelefono1 != null ?
                new ObjectParameter("inTelefono1", inTelefono1) :
                new ObjectParameter("inTelefono1", typeof(string));
    
            var inTelefono2Parameter = inTelefono2 != null ?
                new ObjectParameter("inTelefono2", inTelefono2) :
                new ObjectParameter("inTelefono2", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Persona", inId_PersonaParameter, inNombreParameter, inTipoDocumentoParameter, inDocumento_IdentidadParameter, inFecha_NacimientoParameter, inEmailParameter, inTelefono1Parameter, inTelefono2Parameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Tipo_Cuenta_Ahorros(Nullable<int> inId_Tipo_Cuenta_Ahorros, string inNombre, Nullable<int> inMoneda, Nullable<decimal> inSaldo_Minimo, Nullable<decimal> inMulta_Saldo_Minimo, Nullable<decimal> inCargo_Anual, Nullable<int> inNum_Retiros_Humano, Nullable<int> inNum_Retiros_Automatico, Nullable<decimal> inComision_Humano, Nullable<decimal> inComision_Automatico, Nullable<float> inInteres, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Tipo_Cuenta_AhorrosParameter = inId_Tipo_Cuenta_Ahorros.HasValue ?
                new ObjectParameter("inId_Tipo_Cuenta_Ahorros", inId_Tipo_Cuenta_Ahorros) :
                new ObjectParameter("inId_Tipo_Cuenta_Ahorros", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inMonedaParameter = inMoneda.HasValue ?
                new ObjectParameter("inMoneda", inMoneda) :
                new ObjectParameter("inMoneda", typeof(int));
    
            var inSaldo_MinimoParameter = inSaldo_Minimo.HasValue ?
                new ObjectParameter("inSaldo_Minimo", inSaldo_Minimo) :
                new ObjectParameter("inSaldo_Minimo", typeof(decimal));
    
            var inMulta_Saldo_MinimoParameter = inMulta_Saldo_Minimo.HasValue ?
                new ObjectParameter("inMulta_Saldo_Minimo", inMulta_Saldo_Minimo) :
                new ObjectParameter("inMulta_Saldo_Minimo", typeof(decimal));
    
            var inCargo_AnualParameter = inCargo_Anual.HasValue ?
                new ObjectParameter("inCargo_Anual", inCargo_Anual) :
                new ObjectParameter("inCargo_Anual", typeof(decimal));
    
            var inNum_Retiros_HumanoParameter = inNum_Retiros_Humano.HasValue ?
                new ObjectParameter("inNum_Retiros_Humano", inNum_Retiros_Humano) :
                new ObjectParameter("inNum_Retiros_Humano", typeof(int));
    
            var inNum_Retiros_AutomaticoParameter = inNum_Retiros_Automatico.HasValue ?
                new ObjectParameter("inNum_Retiros_Automatico", inNum_Retiros_Automatico) :
                new ObjectParameter("inNum_Retiros_Automatico", typeof(int));
    
            var inComision_HumanoParameter = inComision_Humano.HasValue ?
                new ObjectParameter("inComision_Humano", inComision_Humano) :
                new ObjectParameter("inComision_Humano", typeof(decimal));
    
            var inComision_AutomaticoParameter = inComision_Automatico.HasValue ?
                new ObjectParameter("inComision_Automatico", inComision_Automatico) :
                new ObjectParameter("inComision_Automatico", typeof(decimal));
    
            var inInteresParameter = inInteres.HasValue ?
                new ObjectParameter("inInteres", inInteres) :
                new ObjectParameter("inInteres", typeof(float));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Tipo_Cuenta_Ahorros", inId_Tipo_Cuenta_AhorrosParameter, inNombreParameter, inMonedaParameter, inSaldo_MinimoParameter, inMulta_Saldo_MinimoParameter, inCargo_AnualParameter, inNum_Retiros_HumanoParameter, inNum_Retiros_AutomaticoParameter, inComision_HumanoParameter, inComision_AutomaticoParameter, inInteresParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Tipo_Moneda(Nullable<int> inId_Tipo_Moneda, string inNombre, string inSimbolo, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Tipo_MonedaParameter = inId_Tipo_Moneda.HasValue ?
                new ObjectParameter("inId_Tipo_Moneda", inId_Tipo_Moneda) :
                new ObjectParameter("inId_Tipo_Moneda", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inSimboloParameter = inSimbolo != null ?
                new ObjectParameter("inSimbolo", inSimbolo) :
                new ObjectParameter("inSimbolo", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Tipo_Moneda", inId_Tipo_MonedaParameter, inNombreParameter, inSimboloParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_TipoDocumento(Nullable<int> inId_TipoDocumento, string inNombre, string inUsuarioACargo, string inIPusuario)
        {
            var inId_TipoDocumentoParameter = inId_TipoDocumento.HasValue ?
                new ObjectParameter("inId_TipoDocumento", inId_TipoDocumento) :
                new ObjectParameter("inId_TipoDocumento", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_TipoDocumento", inId_TipoDocumentoParameter, inNombreParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Usuario(Nullable<int> inId_Usuario, string inNombre_Persona, string inNombre, string inPassword, string inEs_Admin, string inUsuarioACargo, string inIPusuario)
        {
            var inId_UsuarioParameter = inId_Usuario.HasValue ?
                new ObjectParameter("inId_Usuario", inId_Usuario) :
                new ObjectParameter("inId_Usuario", typeof(int));
    
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inPasswordParameter = inPassword != null ?
                new ObjectParameter("inPassword", inPassword) :
                new ObjectParameter("inPassword", typeof(string));
    
            var inEs_AdminParameter = inEs_Admin != null ?
                new ObjectParameter("inEs_Admin", inEs_Admin) :
                new ObjectParameter("inEs_Admin", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Usuario", inId_UsuarioParameter, inNombre_PersonaParameter, inNombreParameter, inPasswordParameter, inEs_AdminParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Actualizar_Usuario_Visualizacion(Nullable<int> inId_Usuario_Visualizacion, string inNombre_Usuario, string inNum_Cuenta, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Usuario_VisualizacionParameter = inId_Usuario_Visualizacion.HasValue ?
                new ObjectParameter("inId_Usuario_Visualizacion", inId_Usuario_Visualizacion) :
                new ObjectParameter("inId_Usuario_Visualizacion", typeof(int));
    
            var inNombre_UsuarioParameter = inNombre_Usuario != null ?
                new ObjectParameter("inNombre_Usuario", inNombre_Usuario) :
                new ObjectParameter("inNombre_Usuario", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Usuario_Visualizacion", inId_Usuario_VisualizacionParameter, inNombre_UsuarioParameter, inNum_CuentaParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Cargar_Beneficiario1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Beneficiario1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Cuentas1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Cuentas1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Estado_Cuenta1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Estado_Cuenta1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Parentezco1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Parentezco1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Personas1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Personas1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Accion(string tipo_Documento, Nullable<int> doc)
        {
            var tipo_DocumentoParameter = tipo_Documento != null ?
                new ObjectParameter("tipo_Documento", tipo_Documento) :
                new ObjectParameter("tipo_Documento", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Accion", tipo_DocumentoParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Cuenta_Ahorros1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Cuenta_Ahorros1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Doc1(string tipo_Documento, Nullable<int> doc)
        {
            var tipo_DocumentoParameter = tipo_Documento != null ?
                new ObjectParameter("tipo_Documento", tipo_Documento) :
                new ObjectParameter("tipo_Documento", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Doc1", tipo_DocumentoParameter, docParameter);
        }
    
        public virtual int Cargar_Tipo_Moneda1(string tipo_Documento, Nullable<int> doc)
        {
            var tipo_DocumentoParameter = tipo_Documento != null ?
                new ObjectParameter("tipo_Documento", tipo_Documento) :
                new ObjectParameter("tipo_Documento", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Tipo_Moneda1", tipo_DocumentoParameter, docParameter);
        }
    
        public virtual int Cargar_Usuarios1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Usuarios1", datosParameter, docParameter);
        }
    
        public virtual int Cargar_Usuarios_Visualizacion1(string datos, Nullable<int> doc)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var docParameter = doc.HasValue ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cargar_Usuarios_Visualizacion1", datosParameter, docParameter);
        }
    
        public virtual int Crear_Beneficiario1(string inNombre_Persona, string inNum_Cuenta, Nullable<int> inNombre_Parentezco, Nullable<float> inPorcentaje, string inUsuarioACargo, string inIPusuario)
        {
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inNombre_ParentezcoParameter = inNombre_Parentezco.HasValue ?
                new ObjectParameter("inNombre_Parentezco", inNombre_Parentezco) :
                new ObjectParameter("inNombre_Parentezco", typeof(int));
    
            var inPorcentajeParameter = inPorcentaje.HasValue ?
                new ObjectParameter("inPorcentaje", inPorcentaje) :
                new ObjectParameter("inPorcentaje", typeof(float));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Beneficiario1", inNombre_PersonaParameter, inNum_CuentaParameter, inNombre_ParentezcoParameter, inPorcentajeParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Cuenta(string inNombre_Persona, string inNombre_Tipo_Cuenta_Ahorros, string inNum_Cuenta, Nullable<System.DateTime> inFecha_Creacion, Nullable<decimal> inSaldo, string inUsuarioACargo, string inIPusuario)
        {
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNombre_Tipo_Cuenta_AhorrosParameter = inNombre_Tipo_Cuenta_Ahorros != null ?
                new ObjectParameter("inNombre_Tipo_Cuenta_Ahorros", inNombre_Tipo_Cuenta_Ahorros) :
                new ObjectParameter("inNombre_Tipo_Cuenta_Ahorros", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inFecha_CreacionParameter = inFecha_Creacion.HasValue ?
                new ObjectParameter("inFecha_Creacion", inFecha_Creacion) :
                new ObjectParameter("inFecha_Creacion", typeof(System.DateTime));
    
            var inSaldoParameter = inSaldo.HasValue ?
                new ObjectParameter("inSaldo", inSaldo) :
                new ObjectParameter("inSaldo", typeof(decimal));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Cuenta", inNombre_PersonaParameter, inNombre_Tipo_Cuenta_AhorrosParameter, inNum_CuentaParameter, inFecha_CreacionParameter, inSaldoParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Estado_Cuenta(string inNum_Cuenta, Nullable<System.DateTime> inFecha_Inicio, Nullable<System.DateTime> inFecha_Fin, Nullable<decimal> inSaldo_Inicial, Nullable<decimal> inSaldo_Final, string inUsuarioACargo, string inIPusuario)
        {
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inFecha_InicioParameter = inFecha_Inicio.HasValue ?
                new ObjectParameter("inFecha_Inicio", inFecha_Inicio) :
                new ObjectParameter("inFecha_Inicio", typeof(System.DateTime));
    
            var inFecha_FinParameter = inFecha_Fin.HasValue ?
                new ObjectParameter("inFecha_Fin", inFecha_Fin) :
                new ObjectParameter("inFecha_Fin", typeof(System.DateTime));
    
            var inSaldo_InicialParameter = inSaldo_Inicial.HasValue ?
                new ObjectParameter("inSaldo_Inicial", inSaldo_Inicial) :
                new ObjectParameter("inSaldo_Inicial", typeof(decimal));
    
            var inSaldo_FinalParameter = inSaldo_Final.HasValue ?
                new ObjectParameter("inSaldo_Final", inSaldo_Final) :
                new ObjectParameter("inSaldo_Final", typeof(decimal));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Estado_Cuenta", inNum_CuentaParameter, inFecha_InicioParameter, inFecha_FinParameter, inSaldo_InicialParameter, inSaldo_FinalParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Parentezco(Nullable<int> inId_Parentezco, string inNombre, string inUsuarioACargo, string inIPusuario)
        {
            var inId_ParentezcoParameter = inId_Parentezco.HasValue ?
                new ObjectParameter("inId_Parentezco", inId_Parentezco) :
                new ObjectParameter("inId_Parentezco", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Parentezco", inId_ParentezcoParameter, inNombreParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Persona(string inNombre, string inTipoDocumento, string inDocumento_Identidad, Nullable<System.DateTime> inFecha_Nacimiento, string inEmail, string inTelefono1, string inTelefono2, string inUsuarioACargo, string inIPusuario)
        {
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inTipoDocumentoParameter = inTipoDocumento != null ?
                new ObjectParameter("inTipoDocumento", inTipoDocumento) :
                new ObjectParameter("inTipoDocumento", typeof(string));
    
            var inDocumento_IdentidadParameter = inDocumento_Identidad != null ?
                new ObjectParameter("inDocumento_Identidad", inDocumento_Identidad) :
                new ObjectParameter("inDocumento_Identidad", typeof(string));
    
            var inFecha_NacimientoParameter = inFecha_Nacimiento.HasValue ?
                new ObjectParameter("inFecha_Nacimiento", inFecha_Nacimiento) :
                new ObjectParameter("inFecha_Nacimiento", typeof(System.DateTime));
    
            var inEmailParameter = inEmail != null ?
                new ObjectParameter("inEmail", inEmail) :
                new ObjectParameter("inEmail", typeof(string));
    
            var inTelefono1Parameter = inTelefono1 != null ?
                new ObjectParameter("inTelefono1", inTelefono1) :
                new ObjectParameter("inTelefono1", typeof(string));
    
            var inTelefono2Parameter = inTelefono2 != null ?
                new ObjectParameter("inTelefono2", inTelefono2) :
                new ObjectParameter("inTelefono2", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Persona", inNombreParameter, inTipoDocumentoParameter, inDocumento_IdentidadParameter, inFecha_NacimientoParameter, inEmailParameter, inTelefono1Parameter, inTelefono2Parameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Tipo_Cuenta_Ahorros(Nullable<int> inId_Tipo_Cuenta_Ahorros, string inNombre, Nullable<int> inMoneda, Nullable<decimal> inSaldo_Minimo, Nullable<decimal> inMulta_Saldo_Minimo, Nullable<decimal> inCargo_Anual, Nullable<int> inNum_Retiros_Humano, Nullable<int> inNum_Retiros_Automatico, Nullable<decimal> inComision_Humano, Nullable<decimal> inComision_Automatico, Nullable<float> inInteres, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Tipo_Cuenta_AhorrosParameter = inId_Tipo_Cuenta_Ahorros.HasValue ?
                new ObjectParameter("inId_Tipo_Cuenta_Ahorros", inId_Tipo_Cuenta_Ahorros) :
                new ObjectParameter("inId_Tipo_Cuenta_Ahorros", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inMonedaParameter = inMoneda.HasValue ?
                new ObjectParameter("inMoneda", inMoneda) :
                new ObjectParameter("inMoneda", typeof(int));
    
            var inSaldo_MinimoParameter = inSaldo_Minimo.HasValue ?
                new ObjectParameter("inSaldo_Minimo", inSaldo_Minimo) :
                new ObjectParameter("inSaldo_Minimo", typeof(decimal));
    
            var inMulta_Saldo_MinimoParameter = inMulta_Saldo_Minimo.HasValue ?
                new ObjectParameter("inMulta_Saldo_Minimo", inMulta_Saldo_Minimo) :
                new ObjectParameter("inMulta_Saldo_Minimo", typeof(decimal));
    
            var inCargo_AnualParameter = inCargo_Anual.HasValue ?
                new ObjectParameter("inCargo_Anual", inCargo_Anual) :
                new ObjectParameter("inCargo_Anual", typeof(decimal));
    
            var inNum_Retiros_HumanoParameter = inNum_Retiros_Humano.HasValue ?
                new ObjectParameter("inNum_Retiros_Humano", inNum_Retiros_Humano) :
                new ObjectParameter("inNum_Retiros_Humano", typeof(int));
    
            var inNum_Retiros_AutomaticoParameter = inNum_Retiros_Automatico.HasValue ?
                new ObjectParameter("inNum_Retiros_Automatico", inNum_Retiros_Automatico) :
                new ObjectParameter("inNum_Retiros_Automatico", typeof(int));
    
            var inComision_HumanoParameter = inComision_Humano.HasValue ?
                new ObjectParameter("inComision_Humano", inComision_Humano) :
                new ObjectParameter("inComision_Humano", typeof(decimal));
    
            var inComision_AutomaticoParameter = inComision_Automatico.HasValue ?
                new ObjectParameter("inComision_Automatico", inComision_Automatico) :
                new ObjectParameter("inComision_Automatico", typeof(decimal));
    
            var inInteresParameter = inInteres.HasValue ?
                new ObjectParameter("inInteres", inInteres) :
                new ObjectParameter("inInteres", typeof(float));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Tipo_Cuenta_Ahorros", inId_Tipo_Cuenta_AhorrosParameter, inNombreParameter, inMonedaParameter, inSaldo_MinimoParameter, inMulta_Saldo_MinimoParameter, inCargo_AnualParameter, inNum_Retiros_HumanoParameter, inNum_Retiros_AutomaticoParameter, inComision_HumanoParameter, inComision_AutomaticoParameter, inInteresParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Tipo_Moneda(Nullable<int> inId_Tipo_Moneda, string inNombre, string inSimbolo, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Tipo_MonedaParameter = inId_Tipo_Moneda.HasValue ?
                new ObjectParameter("inId_Tipo_Moneda", inId_Tipo_Moneda) :
                new ObjectParameter("inId_Tipo_Moneda", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inSimboloParameter = inSimbolo != null ?
                new ObjectParameter("inSimbolo", inSimbolo) :
                new ObjectParameter("inSimbolo", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Tipo_Moneda", inId_Tipo_MonedaParameter, inNombreParameter, inSimboloParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_TipoDocumento(Nullable<int> inId_TipoDocumento, string inNombre, string inUsuarioACargo, string inIPusuario)
        {
            var inId_TipoDocumentoParameter = inId_TipoDocumento.HasValue ?
                new ObjectParameter("inId_TipoDocumento", inId_TipoDocumento) :
                new ObjectParameter("inId_TipoDocumento", typeof(int));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_TipoDocumento", inId_TipoDocumentoParameter, inNombreParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Usuario(string inNombre_Persona, string inNombre, string inPassword, string inEs_Admin, string inUsuarioACargo, string inIPusuario)
        {
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inNombreParameter = inNombre != null ?
                new ObjectParameter("inNombre", inNombre) :
                new ObjectParameter("inNombre", typeof(string));
    
            var inPasswordParameter = inPassword != null ?
                new ObjectParameter("inPassword", inPassword) :
                new ObjectParameter("inPassword", typeof(string));
    
            var inEs_AdminParameter = inEs_Admin != null ?
                new ObjectParameter("inEs_Admin", inEs_Admin) :
                new ObjectParameter("inEs_Admin", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Usuario", inNombre_PersonaParameter, inNombreParameter, inPasswordParameter, inEs_AdminParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Crear_Usuario_Visualizacion(string inNombre_Usuario, string inNum_Cuenta, string inUsuarioACargo, string inIPusuario)
        {
            var inNombre_UsuarioParameter = inNombre_Usuario != null ?
                new ObjectParameter("inNombre_Usuario", inNombre_Usuario) :
                new ObjectParameter("inNombre_Usuario", typeof(string));
    
            var inNum_CuentaParameter = inNum_Cuenta != null ?
                new ObjectParameter("inNum_Cuenta", inNum_Cuenta) :
                new ObjectParameter("inNum_Cuenta", typeof(string));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Crear_Usuario_Visualizacion", inNombre_UsuarioParameter, inNum_CuentaParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Beneficiario1(Nullable<int> inId_Beneficiario, string inUsuarioACargo, string inIPusuario)
        {
            var inId_BeneficiarioParameter = inId_Beneficiario.HasValue ?
                new ObjectParameter("inId_Beneficiario", inId_Beneficiario) :
                new ObjectParameter("inId_Beneficiario", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Beneficiario1", inId_BeneficiarioParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Cuenta(Nullable<int> inId_Cuenta, string inUsuarioACargo, string inIPusuario)
        {
            var inId_CuentaParameter = inId_Cuenta.HasValue ?
                new ObjectParameter("inId_Cuenta", inId_Cuenta) :
                new ObjectParameter("inId_Cuenta", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Cuenta", inId_CuentaParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Estado_Cuenta(Nullable<int> inId_Estado_Cuenta, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Estado_CuentaParameter = inId_Estado_Cuenta.HasValue ?
                new ObjectParameter("inId_Estado_Cuenta", inId_Estado_Cuenta) :
                new ObjectParameter("inId_Estado_Cuenta", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Estado_Cuenta", inId_Estado_CuentaParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Parentezco(Nullable<int> inId_Parentezco, string inUsuarioACargo, string inIPusuario)
        {
            var inId_ParentezcoParameter = inId_Parentezco.HasValue ?
                new ObjectParameter("inId_Parentezco", inId_Parentezco) :
                new ObjectParameter("inId_Parentezco", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Parentezco", inId_ParentezcoParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Persona(Nullable<int> inId_Persona, string inUsuarioACargo, string inIPusuario)
        {
            var inId_PersonaParameter = inId_Persona.HasValue ?
                new ObjectParameter("inId_Persona", inId_Persona) :
                new ObjectParameter("inId_Persona", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Persona", inId_PersonaParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Tipo_Cuenta_Ahorros(Nullable<int> inId_Tipo_Cuenta_Ahorros, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Tipo_Cuenta_AhorrosParameter = inId_Tipo_Cuenta_Ahorros.HasValue ?
                new ObjectParameter("inId_Tipo_Cuenta_Ahorros", inId_Tipo_Cuenta_Ahorros) :
                new ObjectParameter("inId_Tipo_Cuenta_Ahorros", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Tipo_Cuenta_Ahorros", inId_Tipo_Cuenta_AhorrosParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Tipo_Moneda(Nullable<int> inId_Tipo_Moneda, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Tipo_MonedaParameter = inId_Tipo_Moneda.HasValue ?
                new ObjectParameter("inId_Tipo_Moneda", inId_Tipo_Moneda) :
                new ObjectParameter("inId_Tipo_Moneda", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Tipo_Moneda", inId_Tipo_MonedaParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_TipoDocumento(Nullable<int> inId_TipoDocumento, string inUsuarioACargo, string inIPusuario)
        {
            var inId_TipoDocumentoParameter = inId_TipoDocumento.HasValue ?
                new ObjectParameter("inId_TipoDocumento", inId_TipoDocumento) :
                new ObjectParameter("inId_TipoDocumento", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_TipoDocumento", inId_TipoDocumentoParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Usuario(Nullable<int> inId_Usuario, string inUsuarioACargo, string inIPusuario)
        {
            var inId_UsuarioParameter = inId_Usuario.HasValue ?
                new ObjectParameter("inId_Usuario", inId_Usuario) :
                new ObjectParameter("inId_Usuario", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Usuario", inId_UsuarioParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Eliminar_Usuario_Visualizacion(Nullable<int> inId_Usuario_Visualizacion, string inUsuarioACargo, string inIPusuario)
        {
            var inId_Usuario_VisualizacionParameter = inId_Usuario_Visualizacion.HasValue ?
                new ObjectParameter("inId_Usuario_Visualizacion", inId_Usuario_Visualizacion) :
                new ObjectParameter("inId_Usuario_Visualizacion", typeof(int));
    
            var inUsuarioACargoParameter = inUsuarioACargo != null ?
                new ObjectParameter("inUsuarioACargo", inUsuarioACargo) :
                new ObjectParameter("inUsuarioACargo", typeof(string));
    
            var inIPusuarioParameter = inIPusuario != null ?
                new ObjectParameter("inIPusuario", inIPusuario) :
                new ObjectParameter("inIPusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_Usuario_Visualizacion", inId_Usuario_VisualizacionParameter, inUsuarioACargoParameter, inIPusuarioParameter);
        }
    
        public virtual int Insertar_BitacoraAcciones(string inNombre_Persona, Nullable<int> inId_Tipo_Accion, Nullable<int> inId_Objeto_Accion, string inQuien_Inserto, string inInsertado_Por, Nullable<System.DateTime> inInserto_El)
        {
            var inNombre_PersonaParameter = inNombre_Persona != null ?
                new ObjectParameter("inNombre_Persona", inNombre_Persona) :
                new ObjectParameter("inNombre_Persona", typeof(string));
    
            var inId_Tipo_AccionParameter = inId_Tipo_Accion.HasValue ?
                new ObjectParameter("inId_Tipo_Accion", inId_Tipo_Accion) :
                new ObjectParameter("inId_Tipo_Accion", typeof(int));
    
            var inId_Objeto_AccionParameter = inId_Objeto_Accion.HasValue ?
                new ObjectParameter("inId_Objeto_Accion", inId_Objeto_Accion) :
                new ObjectParameter("inId_Objeto_Accion", typeof(int));
    
            var inQuien_InsertoParameter = inQuien_Inserto != null ?
                new ObjectParameter("inQuien_Inserto", inQuien_Inserto) :
                new ObjectParameter("inQuien_Inserto", typeof(string));
    
            var inInsertado_PorParameter = inInsertado_Por != null ?
                new ObjectParameter("inInsertado_Por", inInsertado_Por) :
                new ObjectParameter("inInsertado_Por", typeof(string));
    
            var inInserto_ElParameter = inInserto_El.HasValue ?
                new ObjectParameter("inInserto_El", inInserto_El) :
                new ObjectParameter("inInserto_El", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insertar_BitacoraAcciones", inNombre_PersonaParameter, inId_Tipo_AccionParameter, inId_Objeto_AccionParameter, inQuien_InsertoParameter, inInsertado_PorParameter, inInserto_ElParameter);
        }
    }
}
