//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseTec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int Id_Beneficiario { get; set; }
        public int Id_Persona { get; set; }
        public int Id_Cuenta { get; set; }
        public int Id_Parentezco { get; set; }
        public float Porcentaje { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Parentezco Parentezco { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
