//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseTec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Cuenta_Ahorros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Cuenta_Ahorros()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public int Id_Tipo_Cuenta_Ahorros { get; set; }
        public string Nombre { get; set; }
        public int Id_Tipo_Moneda { get; set; }
        public decimal Saldo_Minimo { get; set; }
        public decimal Multa_Saldo_Minimo { get; set; }
        public decimal Cargo_Anual { get; set; }
        public int Num_Retiros_Humano { get; set; }
        public int Num_Retiros_Automatico { get; set; }
        public decimal Comision_Humano { get; set; }
        public decimal Comision_Automatico { get; set; }
        public float Interes { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        public virtual Tipo_Moneda Tipo_Moneda { get; set; }
    }
}
