USE BD1
ALTER TABLE dbo.Beneficiario DISABLE TRIGGER ALL
ALTER TABLE dbo.Bitacora_Accion DISABLE TRIGGER ALL
ALTER TABLE dbo.Cuenta DISABLE TRIGGER ALL
ALTER TABLE dbo.Estado_Cuenta DISABLE TRIGGER ALL
ALTER TABLE dbo.Parentezco DISABLE TRIGGER ALL
ALTER TABLE dbo.Persona DISABLE TRIGGER ALL

ALTER TABLE dbo.Tipo_Accion DISABLE TRIGGER ALL
ALTER TABLE dbo.Tipo_Cuenta_Ahorros DISABLE TRIGGER ALL
ALTER TABLE dbo.Tipo_Documento DISABLE TRIGGER ALL
ALTER TABLE dbo.Tipo_Moneda DISABLE TRIGGER ALL
ALTER TABLE dbo.Usuario DISABLE TRIGGER ALL
ALTER TABLE dbo.Usuario_Visualizacion DISABLE TRIGGER ALL
GO
